# Aliases

# Ansible
#alias avv='ansible-vault view'
#alias ave='ansible-vault edit'

# Dir
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias diff='diff --color -u'

# Dmesg
alias dmesg='dmesg --human --color=always'

# Grep
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto' 

# Info
alias info='info --vi-keys'

# iproute2
alias ip='ip -color'

# Clear
alias k='clear'

# List
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls -h --color=auto'
alias lx='ls -X'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

# Navigation
alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Neofetch
alias neofetch='neofetch --disable Model Uptime --colors 4 4 2 6 3 7 --ascii_colors 2 1'

# Python
alias shttp='python3 -m http.server'

# Quit
alias q='exit'

# rsync
alias rsync='rsync --progress --partial --archive --compress --stats --executability --hard-links'

# Python http server
alias shttp='python3 -m http.server'

# Sudo
alias sudo='sudo '

# Typos
alias celar='clear'
alias cleawr='clear'

# Utilities
alias tb='nc termbin.com 9999'
alias wget='wget -c'

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
